### ISSUE TITLE
Missing Resources

### ISSUE THREAD

**Issue by Gusher** [hgouveia/godot-blank-starter-template-3d#1]
When trying open get missing resources errors..
<img width="389" alt="Capture" src="https://user-images.githubusercontent.com/261646/112101649-407f3100-8b64-11eb-9ab4-bbc47fe51451.PNG">

**Comment by hgouveia** [comment]
Hello @Gusher , could you detail which Godot version, and OS? , also how can you show me the folder tree?

**Comment by Gusher** [comment]
was using godot 3.2.3, win 10 64bit, but am gonna try again.... was it made only for ver. 3.1?

**Comment by hgouveia** [comment]
@Gusher , not, this should work for any 3.X godot version, 

i just tried with 3.2.3 x64 Win10, downloading the code as a zip from github and i was able to imported it and run it successfully, i also tried downloaded from the Release section, same result , imported it and run it successfully, and also did it directly from the built-in Asset Library (https://godotengine.org/asset-library/asset/356) , and i was able to create it and run it successfully

My only guess could be a Permission issues?

**Comment by Gusher** [comment]
All good, just realized it's best to import, not install manually... very nice demo! I hope to see an update on this  template... perhaps mouse support to be able to navigate when playing...

**Comment by hgouveia** [comment]
@Gusher  glad to hear, 

Yeap i think that would be a nice addition aswell, i will think about it, i am also thinking to upgrade it to Godot 4 when is fully released

**Comment by hgouveia** [comment]
@Gusher  updated to 1.0.2 , download it from Released, and reimport, it will now support mouse camera movement

**Comment by Gusher** [comment]
..ok, thanks alot!
